### ISSUE TITLE
Setting of base_url may not be used

### ISSUE THREAD

**Issue by yoshiaki-u** [StackStorm-Exchange/stackstorm-github#10]
I want to use this pack in a URL except the https://github .com .
But, I think that setting of base_url is not used.
I made the following modifications. Is this a good change?
 /github/sensors/github_repository_sensor.py 

          def setup(self):
              # Empty string '' is not ok but None is fine. (Sigh)
     -        self._client = Github(self._config.get('token', None) or None)
     +        config_base_url = self._config.get('base_url', None) or None
     +        config_user     = self._config.get('user', None) or None
     +        config_token    = self._config.get('token', None) or None
     +        #self._client = Github(self._config.get('token', None) or None)
     +        self._client = Github(config_token or None, base_url=config_base_url)
     
              repository_sensor = self._config.get('repository_sensor', None)
              if repository_sensor is None:

**Comment by LindsayHill** [comment]
Hi @yoshiaki-u - yes, that could be a good change. It looks like we added `base_url` support for actions, but not for the sensor. Could you submit a Pull Request with this?

**Comment by yoshiaki-u** [comment]
Hello @LindsayHill,
Thank you for your comment.
I will submit Pull Request with this.
Please examin it.
