### ISSUE TITLE
Deployment events fail as deploy_payload is immutable

### ISSUE THREAD

**Issue by jjm** [StackStorm-Exchange/stackstorm-github#3]
When attempting to use the `github.deployment_event` webhook it fails with the following error:

```
ValueError: Override of immutable parameter(s) [u'deploy_payload'] is unsupported
```

The `immutable: true` arg to `deploy_payload` needs removed.

**Comment by emedvedev** [comment]
Oh! Thanks, must've overlooked this. Would you be interested in submitting a PR? :)

**Comment by jjm** [comment]
No worries already done ;-) Plus it was in the action I wrote :-(
